stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: npm i && npm run build
      displayName: 'Build the dashboard'
      workingDirectory: src/dashboard

    - task: PublishBuildArtifacts@1
      displayName: 'Publish dashboard artifact'
      inputs: 
        PathtoPublish: src/dashboard/dist
        ArtifactName: src/dashboard/dist

    - task: PublishBuildArtifacts@1
      displayName: 'Publish infrastructure artifact'
      inputs: 
        PathtoPublish: infrastructure
        ArtifactName: infrastructure

    - task: PublishBuildArtifacts@1
      displayName: 'Publish architecture artifact'
      inputs: 
        PathtoPublish: architecture
        ArtifactName: architecture
- stage: Deploy
  jobs:
  - deployment: DeployWeb
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'DEV'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment
