# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm i && npm run build
  displayName: 'Build the dashboard'
  workingDirectory: src/dashboard

- task: PublishBuildArtifacts@1
  displayName: 'Publish dashboard artifact'
  inputs: 
    PathtoPublish: src/dashboard/dist
    ArtifactName: src/dashboard/dist
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish infrastructure artifact'
  inputs: 
    PathtoPublish: infrastructure
    ArtifactName: infrastructure
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish architecture artifact'
  inputs: 
    PathtoPublish: architecture
    ArtifactName: architecture
